// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package maskinporten

import "time"

type OidcClientResponse struct {
	// Levetid i sekunder for utstedt access_token
	AccessTokenLifetime *int `json:"access_token_lifetime,omitempty" yaml:"access_token_lifetime,omitempty" mapstructure:"access_token_lifetime,omitempty"`

	// Intern status for å aktivere/deaktivere klient. Blir generert av systemet
	Active *bool `json:"active,omitempty" yaml:"active,omitempty" mapstructure:"active,omitempty"`

	// Applikasjonstype
	ApplicationType *OidcClientResponseApplicationType `json:"application_type,omitempty" yaml:"application_type,omitempty" mapstructure:"application_type,omitempty"`

	// Levetid for registrert autorisasjon i sekunder. I en OpenID Connect sammenheng
	// vil dette være tilgangen til userinfo-endepunktet.
	AuthorizationLifetime *int `json:"authorization_lifetime,omitempty" yaml:"authorization_lifetime,omitempty" mapstructure:"authorization_lifetime,omitempty"`

	// client_id som brukes sammen med secret i en basic http authentication mot token
	// endepunktet. Blir generert av systemet
	ClientId string `json:"client_id" yaml:"client_id" mapstructure:"client_id"`

	// For interne skyapplikasjoner. Klientens logouri
	ClientLogoUri *string `json:"client_logo_uri,omitempty" yaml:"client_logo_uri,omitempty" mapstructure:"client_logo_uri,omitempty"`

	// Navn på klient, blir vist ved innlogging
	ClientName string `json:"client_name" yaml:"client_name" mapstructure:"client_name"`

	// For interne skyapplikasjoner. Klienten sin org beskrivelse
	ClientOrgDescription *string `json:"client_org_description,omitempty" yaml:"client_org_description,omitempty" mapstructure:"client_org_description,omitempty"`

	// For interne skyapplikasjoner. Klienten sitt organisasjonsnnavn
	ClientOrgName *string `json:"client_org_name,omitempty" yaml:"client_org_name,omitempty" mapstructure:"client_org_name,omitempty"`

	// Klienten sitt organisasjonsnummer.
	ClientOrgno string `json:"client_orgno" yaml:"client_orgno" mapstructure:"client_orgno"`

	// Secret som brukes sammen med client_id i en basic http authentication mot token
	// endepunktet. Blir generert av systemet
	ClientSecret *string `json:"client_secret,omitempty" yaml:"client_secret,omitempty" mapstructure:"client_secret,omitempty"`

	// URL til klient (blir brukt på tilbake-knapp og ved feil)
	ClientUri *string `json:"client_uri,omitempty" yaml:"client_uri,omitempty" mapstructure:"client_uri,omitempty"`

	// Code challenge method for PKCE. Gyldige verdier er none eller s256. Dette er
	// kun relevant for OpenID Connect. Om ikke satt, vil default bli S256.
	CodeChallengeMethod *OidcClientResponseCodeChallengeMethod `json:"code_challenge_method,omitempty" yaml:"code_challenge_method,omitempty" mapstructure:"code_challenge_method,omitempty"`

	// Created corresponds to the JSON schema field "created".
	Created *time.Time `json:"created,omitempty" yaml:"created,omitempty" mapstructure:"created,omitempty"`

	// Beskrivelse av klienten, ikke synlig for innbyggere, men blir lagret i Difis
	// støttesystemer
	Description string `json:"description" yaml:"description" mapstructure:"description"`

	// Flagg som bestemmer om parameterne for issuer og sesjons-id skal sendes med
	// frontchannel_logout_uri
	FrontchannelLogoutSessionRequired *bool `json:"frontchannel_logout_session_required,omitempty" yaml:"frontchannel_logout_session_required,omitempty" mapstructure:"frontchannel_logout_session_required,omitempty"`

	// URL som provideren sender request til ved utlogging trigget av annen klient i
	// samme sesjon
	FrontchannelLogoutUri *string `json:"frontchannel_logout_uri,omitempty" yaml:"frontchannel_logout_uri,omitempty" mapstructure:"frontchannel_logout_uri,omitempty"`

	// Tillatte Grant Types for klient. Implicit skal ikke tas i bruk av nye
	// klienter(deprecated).
	GrantTypes []OidcClientResponseGrantTypesElem `json:"grant_types" yaml:"grant_types" mapstructure:"grant_types"`

	// Integrasjonstype
	IntegrationType *OidcClientResponseIntegrationType `json:"integration_type,omitempty" yaml:"integration_type,omitempty" mapstructure:"integration_type,omitempty"`

	// Uri til JWKS om satt. Kan kun leses ut, ikke settes.
	JwksUri *string `json:"jwks_uri,omitempty" yaml:"jwks_uri,omitempty" mapstructure:"jwks_uri,omitempty"`

	// LastUpdated corresponds to the JSON schema field "last_updated".
	LastUpdated *time.Time `json:"last_updated,omitempty" yaml:"last_updated,omitempty" mapstructure:"last_updated,omitempty"`

	// LogoUri corresponds to the JSON schema field "logo_uri".
	LogoUri *string `json:"logo_uri,omitempty" yaml:"logo_uri,omitempty" mapstructure:"logo_uri,omitempty"`

	// Liste over url’er som provideren redirecter til etter fullført utlogging
	PostLogoutRedirectUris []string `json:"post_logout_redirect_uris,omitempty" yaml:"post_logout_redirect_uris,omitempty" mapstructure:"post_logout_redirect_uris,omitempty"`

	// Liste over gyldige url’er som provideren kan redirecte tilbake til etter
	// vellykket autorisasjonsforespørsel
	RedirectUris []string `json:"redirect_uris,omitempty" yaml:"redirect_uris,omitempty" mapstructure:"redirect_uris,omitempty"`

	// Levetid i sekunder for utstedt refresh_token
	RefreshTokenLifetime *int `json:"refresh_token_lifetime,omitempty" yaml:"refresh_token_lifetime,omitempty" mapstructure:"refresh_token_lifetime,omitempty"`

	// Ved REUSE kan refresh_token benyttes flere ganger.  Ved ONETIME kan
	// refresh_token kun benyttes en gang.
	RefreshTokenUsage *OidcClientResponseRefreshTokenUsage `json:"refresh_token_usage,omitempty" yaml:"refresh_token_usage,omitempty" mapstructure:"refresh_token_usage,omitempty"`

	// Liste over scopes som klienten kan forespørre. For OpenID Connect er aktuelle
	// scopes openid og profile. For API-sikring, ta kontakt med oss
	Scopes []string `json:"scopes,omitempty" yaml:"scopes,omitempty" mapstructure:"scopes,omitempty"`

	// Flagg for å disable sso. Dette vil gjøre at brukeren må logge inn på nytt for
	// din klient. Dette er kun relevant for OpenID Connect. Om ikke satt, vil default
	// være false for ID-porten og true for Ansattporten
	SsoDisabled *bool `json:"sso_disabled,omitempty" yaml:"sso_disabled,omitempty" mapstructure:"sso_disabled,omitempty"`

	// Leverandøren sitt organisasjonsnummer
	SupplierOrgno *string `json:"supplier_orgno,omitempty" yaml:"supplier_orgno,omitempty" mapstructure:"supplier_orgno,omitempty"`

	// Autentiseringsmetode for klient. None anbefales for klienter som kjører i
	// nettleser eller på mobil
	TokenEndpointAuthMethod *OidcClientResponseTokenEndpointAuthMethod `json:"token_endpoint_auth_method,omitempty" yaml:"token_endpoint_auth_method,omitempty" mapstructure:"token_endpoint_auth_method,omitempty"`
}

type OidcClientResponseApplicationType string

const OidcClientResponseApplicationTypeBrowser OidcClientResponseApplicationType = "browser"
const OidcClientResponseApplicationTypeNative OidcClientResponseApplicationType = "native"
const OidcClientResponseApplicationTypeWeb OidcClientResponseApplicationType = "web"

type OidcClientResponseCodeChallengeMethod string

const OidcClientResponseCodeChallengeMethodNone OidcClientResponseCodeChallengeMethod = "none"
const OidcClientResponseCodeChallengeMethodS256 OidcClientResponseCodeChallengeMethod = "S256"

type OidcClientResponseGrantTypesElem string

const OidcClientResponseGrantTypesElemAuthorizationCode OidcClientResponseGrantTypesElem = "authorization_code"
const OidcClientResponseGrantTypesElemImplicit OidcClientResponseGrantTypesElem = "implicit"
const OidcClientResponseGrantTypesElemRefreshToken OidcClientResponseGrantTypesElem = "refresh_token"
const OidcClientResponseGrantTypesElemUrnIetfParamsOauthGrantTypeJwtBearer OidcClientResponseGrantTypesElem = "urn:ietf:params:oauth:grant-type:jwt-bearer"

type OidcClientResponseIntegrationType string

const OidcClientResponseIntegrationTypeAnsattporten OidcClientResponseIntegrationType = "ansattporten"
const OidcClientResponseIntegrationTypeApiKlient OidcClientResponseIntegrationType = "api_klient"
const OidcClientResponseIntegrationTypeConnect2Norway OidcClientResponseIntegrationType = "connect2norway"
const OidcClientResponseIntegrationTypeEformidling OidcClientResponseIntegrationType = "eformidling"
const OidcClientResponseIntegrationTypeIdporten OidcClientResponseIntegrationType = "idporten"
const OidcClientResponseIntegrationTypeIdportenSaml2 OidcClientResponseIntegrationType = "idporten_saml2"
const OidcClientResponseIntegrationTypeKrr OidcClientResponseIntegrationType = "krr"
const OidcClientResponseIntegrationTypeMaskinporten OidcClientResponseIntegrationType = "maskinporten"

type OidcClientResponseRefreshTokenUsage string

const OidcClientResponseRefreshTokenUsageONETIME OidcClientResponseRefreshTokenUsage = "ONETIME"
const OidcClientResponseRefreshTokenUsageREUSE OidcClientResponseRefreshTokenUsage = "REUSE"

type OidcClientResponseTokenEndpointAuthMethod string

const OidcClientResponseTokenEndpointAuthMethodClientSecretBasic OidcClientResponseTokenEndpointAuthMethod = "client_secret_basic"
const OidcClientResponseTokenEndpointAuthMethodClientSecretPost OidcClientResponseTokenEndpointAuthMethod = "client_secret_post"
const OidcClientResponseTokenEndpointAuthMethodNone OidcClientResponseTokenEndpointAuthMethod = "none"
const OidcClientResponseTokenEndpointAuthMethodPrivateKeyJwt OidcClientResponseTokenEndpointAuthMethod = "private_key_jwt"
