# permissions for end users to view maskinportenclients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: maskinportenclient-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: altinn-k8s-operator
    app.kubernetes.io/part-of: altinn-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: maskinportenclient-viewer-role
rules:
- apiGroups:
  - resources.altinn.studio
  resources:
  - maskinportenclients
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - resources.altinn.studio
  resources:
  - maskinportenclients/status
  verbs:
  - get
